WildCard.out: WildCard.cpp 
	g++ -std=c++11 -o WildCard.out WildCard.cpp
TrianglePath.out: TrianglePath.cpp 
	g++ -std=c++11 -o TrianglePath.out TrianglePath.cpp
clean:
	rm -rf *.o
	rm -rf *.gch
	rm -rf *.out