WildCard.out: WildCard.cpp 
	g++ -std=c++11 -o WildCard.out WildCard.cpp
TrianglePath.out: TrianglePath.cpp 
	g++ -std=c++11 -o TrianglePath.out TrianglePath.cpp
LIS.out: LIS.cpp 
	g++ -std=c++11 -o LIS.out LIS.cpp
PI.out: PI.cpp 
	g++ -std=c++11 -o PI.out PI.cpp
Quantization.out: Quantization.cpp 
	g++ -std=c++11 -o Quantization.out Quantization.cpp
clean:
	rm -rf *.o
	rm -rf *.gch
	rm -rf *.out