Traversal.out: Traversal.cpp 
	g++ -std=c++11 -o Traversal.out Traversal.cpp

4256.out: 4256.cpp 
	g++ -std=c++11 -o 4256.out 4256.cpp

test.out: test.cpp 
	g++ -std=c++11 -o test.out test.cpp

Fortress.out: Fortress.cpp 
	g++ -std=c++11 -o Fortress.out Fortress.cpp

NERD2.out: NERD2.cpp 
	g++ -std=c++11 -o NERD2.out NERD2.cpp

Treap.out: Treap.cpp 
	g++ -std=c++11 -o Treap.out Treap.cpp


clean:
	rm -rf *.o
	rm -rf *.gch
	rm -rf *.out